default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  ports: 5432
  username: postgres
  password: root

development:
  <<: *default
  database: myappv2_development

test:
  <<: *default
  database: myappv2_test

production:
  <<: *default
  database: myappv2_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
